### ISSUE TITLE
gradle vs gradlew

### ISSUE THREAD

**Issue by judiMc** [sci-oer/automated-builder#39]
There will be at least 20 example projects included with the container, probably more.  I'm concerned about the impact on container size if we include multiple sets  of gradle wrapper files.   thoughts?

**Comment by MarshallAsch** [comment]
I think this is related to: https://github.com/sci-oer/oo-resources/issues/15 where there is also the potential runtime issue of the projects needing to fetch all the gradle dependancies when the student may not have internet access. 

the `gradle` executable is installed and configured in the container so it _could_ be used instead of including the gradlew wrapper in each project.

**Comment by MarshallAsch** [comment]
This issue was created before the build in `gradle` command was automatically loaded into the path
